"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { FiArrowLeft, FiInbox, FiRefreshCw, FiSearch } from "react-icons/fi";
import type { User } from "@/lib/auth";
import { Logo } from "./logo";
import { LogoutButton } from "./logout-button";
import s from "./admin-support.module.css";

type Status="OPEN"|"IN_PROGRESS"|"RESOLVED";
type Ticket={id:string;topic:string;message:string;status:Status;createdAt:string;user:{displayName:string;email:string}};

async function request<T>(path:string,options?:RequestInit):Promise<T>{const response=await fetch(`/api/dashboard/admin/${path}`,{...options,headers:{...(options?.body?{"Content-Type":"application/json"}:{}),...options?.headers}});const data=await response.json();if(!response.ok)throw new Error(data.error||"Request failed");return data}

export function AdminSupport({user}:{user:User}){const[tickets,setTickets]=useState<Ticket[]>([]);const[query,setQuery]=useState("");const[filter,setFilter]=useState<Status|"ALL">("ALL");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const load=useCallback(async()=>{setLoading(true);setError("");try{const data=await request<{tickets:Ticket[]}>("tickets");setTickets(data.tickets)}catch(e){setError(e instanceof Error?e.message:"Unable to load tickets")}finally{setLoading(false)}},[]);useEffect(()=>{queueMicrotask(()=>void load())},[load]);async function update(id:string,status:Status){try{await request(`tickets/${id}`,{method:"POST",body:JSON.stringify({status})});setTickets(current=>current.map(ticket=>ticket.id===id?{...ticket,status}:ticket))}catch(e){setError(e instanceof Error?e.message:"Unable to update ticket")}}const visible=useMemo(()=>tickets.filter(ticket=>(filter==="ALL"||ticket.status===filter)&&`${ticket.topic} ${ticket.message} ${ticket.user.displayName} ${ticket.user.email}`.toLowerCase().includes(query.toLowerCase())),[tickets,filter,query]);return <main className={s.shell}><header><Logo/><nav><Link href="/dashboard"><FiArrowLeft/>Client dashboard</Link><span>{user.displayName}</span><LogoutButton/></nav></header><section className={s.hero}><div><p>NickHub operations</p><h1>Support inbox</h1><span>Review and manage messages submitted by every client.</span></div><button onClick={()=>void load()}><FiRefreshCw/>Refresh</button></section><section className={s.controls}><label><FiSearch/><input aria-label="Search support tickets" onChange={e=>setQuery(e.target.value)} placeholder="Search client, email, topic, or message" value={query}/></label><div>{(["ALL","OPEN","IN_PROGRESS","RESOLVED"] as const).map(value=><button className={filter===value?s.active:""} key={value} onClick={()=>setFilter(value)}>{value.replaceAll("_"," ")}</button>)}</div></section>{error&&<p className={s.error}>{error}</p>}{loading?<div className={s.empty}>Loading support messages…</div>:visible.length?<section className={s.grid}>{visible.map(ticket=><article key={ticket.id}><div className={s.ticketHead}><div><span>{ticket.topic}</span><h2>{ticket.user.displayName}</h2><a href={`mailto:${ticket.user.email}`}>{ticket.user.email}</a></div><b className={s[ticket.status.toLowerCase()]}>{ticket.status.replaceAll("_"," ")}</b></div><p>{ticket.message}</p><footer><time dateTime={ticket.createdAt}>{new Date(ticket.createdAt).toLocaleString()}</time><label>Status<select value={ticket.status} onChange={e=>void update(ticket.id,e.target.value as Status)}><option value="OPEN">Open</option><option value="IN_PROGRESS">In progress</option><option value="RESOLVED">Resolved</option></select></label></footer></article>)}</section>:<div className={s.empty}><FiInbox/><h2>No support messages found</h2><p>New client tickets will appear here automatically.</p></div>}</main>}
